apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-try-2020-2
  region: ap-northeast-1
  version: "1.18"
vpc:
  cidr: "192.168.48.0/21"
iam:
  withOIDC: true
managedNodeGroups:
  - name: mng-1
    instanceType: m5.xlarge
    minSize: 2
    desiredCapacity: 2
    maxSize: 2
    volumeSize: 200
    ssh:
      publicKeyName: "my-key-pair"
