apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-try-2020-1
  region: ap-northeast-1
  version: "1.18"
iam:
  withOIDC: true
managedNodeGroups:
  - name: mng-1
    instanceType: m5.xlarge
    minSize: 2
    desiredCapacity: 2
    maxSize: 2
    volumeSize: 200
    ssh:
      publicKeyName: 'my-key-pair'
